global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # üîπ –í–∞—Ä–∏–∞–Ω—Ç A: FastStream –≤ Docker (—Ä–∞—Å–∫–æ–º–º–µ–Ω—Ç–∏—Ä—É–π, –∫–æ–≥–¥–∞ –∑–∞–ø—É—Å–∫–∞–µ—à—å —á–µ—Ä–µ–∑ docker-compose)
  - job_name: "fs_subscriber-docker"
    metrics_path: /metrics  # –ø–æ—á–µ–º—É—Ç–æ /metrics –Ω–µ —Ä–∞–±–æ—Ç–∞–µ—Ç -> —Ä–µ–¥–∏—Ä–µ–∫—Ç –Ω–∞ /metrics/
    static_configs:
      - targets: ["app_template_rag:8080"]  # ‚Üê –∏–º—è —Å–µ—Ä–≤–∏—Å–∞ –≤ docker-compose



##  # üîπ –í–∞—Ä–∏–∞–Ω—Ç B: FastStream –Ω–∞ —Ö–æ—Å—Ç–µ (—Ä–∞—Å–∫–æ–º–º–µ–Ω—Ç–∏—Ä—É–π, –∫–æ–≥–¥–∞ –∑–∞–ø—É—Å–∫–∞–µ—à—å –ª–æ–∫–∞–ª—å–Ω–æ)
#   - job_name: "faststream-local"
#     metrics_path: /metrics
#     static_configs:
#       - targets: ["host.docker.internal:8080"]